### ISSUE TITLE
TypeError when calling glm-4-9b-chat (cannot use a string pattern on a bytes-like object)

### ISSUE THREAD

**Issue by sci-m-wang** [outlines-dev/outlines#1038]
### Describe the issue as clearly as possible:

When I use outlines to call `glm-4-9b-chat` to operate the classification task, I met the error that "cannot use a string pattern on a bytes-like object".

### Steps/code to reproduce the bug:

```python
from outlines import models, generate
from transformers import AutoModelForCausalLM, AutoTokenizer

llm = AutoModelForCausalLM.from_pretrained(f"/datas/huggingface/{model_name}",trust_remote_code=True, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(f"/datas/huggingface/{model_name}", trust_remote_code=True)

model = models.Transformers(llm,tokenizer)
generator = generate.choice(model,["positive","negative"])
```

### Expected result:

```shell
positive OR negative
```

### Error message:

```shell
Traceback (most recent call last):
  File "/datas/wangm/seeker_status/test_classification_glm.py", line 17, in <module>
    generator = generate.choice(model,["positive","negative"])
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/site-packages/outlines/generate/choice.py", line 17, in choice
    generator = regex(model, regex_str, sampler)
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/site-packages/outlines/generate/regex.py", line 33, in regex
    fsm = RegexGuide(regex_str, model.tokenizer)
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/site-packages/outlines/fsm/guide.py", line 145, in __init__
    ) = create_states_mapping(regex_string, tokenizer)
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/site-packages/outlines/caching.py", line 122, in wrapper
    result = cached_function(*args, **kwargs)
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/site-packages/outlines/fsm/guide.py", line 118, in create_states_mapping
    states_to_token_maps, empty_token_ids = create_fsm_index_tokenizer(
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/site-packages/outlines/fsm/regex.py", line 898, in create_fsm_index_tokenizer
    vocabulary, empty_token_ids = reduced_vocabulary(tokenizer)
  File "/datas/wangm/.conda/envs/llama/lib/python3.10/site-packages/outlines/fsm/regex.py", line 846, in reduced_vocabulary
    if "\ufffd" in token_str and not re_replacement_seq.match(token):
TypeError: cannot use a string pattern on a bytes-like object
```

### Outlines/Python version information:

Version information
<details>
```
0.0.46
Python 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
```
</details>

### Context for the issue:

Upon my testing, the error occurs in the `generator = generate.choice(model,["positive", "negative"])` line of code.

**Comment by KawshikManikantan** [comment]
Hi, 
This is observed also in the regex generator for this model (`outlines.generate.regex(model, decoding_regex, sampler=sampler`)). @rlouf it would be great if you could please look into this. Always thankful for your great contribution.

**Comment by Dong148** [comment]
Same problems in vLLM "response_format": {"type": "json_object"}

**Comment by abaveja313** [comment]
Anyone have a workaround?

**Comment by XxxAtlantis** [comment]
I had the same problem with a glm4-9b model !

**Comment by abaveja313** [comment]
@XxxAtlantis any luck in figuring out a workaround?

**Comment by duming** [comment]
I have got the same error and dived into the code and glm tokenizer a bit.
I think the direct cause of the error is that glm tokenizer dose not strictly follow the definition of transformers get_vocab().
https://huggingface.co/docs/transformers/v4.44.0/en/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.get_vocab
get_vocab returns vocabulary in string format, and outlines use string utilities such as startswith to process LLM vocabulary and then build fsm. However the get_vocab function of **glm tokenizer return vocabulary in byte**, which is not compatible with string utilities.

But you can not fix the bug by simply convert byte vocabulary to string. I have tried and found out that there are parts of the glm vacabulary can not be convert to utf-8 string. It turns out that qwen and glm using **BPE** tokenization technique,  some of the token  are just not valid utf-8 encoding. https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md. 

conclusion:
1. The error can only be resolved by Outlines supporting BPE bytes tokens.
2. Chinese LLM such as Internlm which does not use BPE are more compatible with outlines.

**Comment by lapp0** [comment]
I have a simple fix. It appears that these follow the pattern of Outlines BPE handling, but they explicitly use the bytes in the tokenizer rather than padding and converting to a string.

```
from outlines import models, generate
from transformers import AutoModelForCausalLM, AutoTokenizer
 
model_name = 
 
llm = AutoModelForCausalLM.from_pretrained("THUDM/glm-4-9b-chat",trust_remote_code=True, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4-9b-chat", trust_remote_code=True)
 
model = models.Transformers(llm,tokenizer)

generator = generate.choice(model, ['和长', '本代模'])
input = '我们在一些经典任务上对 GLM-4-9B-Chat 模型进行了评测,并得到了如下的结果'

print(generator(input))
# '和长'
```

Could you please help me test [this PR](https://github.com/dottxt-ai/outlines/pull/1153) and ensure it resolves the issues you all have been seeing?

Preview:
```
pip install git+https://github.com/lapp0/outlines@fix-bpe
```

**Comment by sci-m-wang** [comment]
> I have a simple fix for the issue.
> 
> It seems `glm-4-9b-chat`s tokenizer uses BPE slightly differently from the LLaMA-style BPE. Specifically, glm-4-9b's tokenizer explicitly uses bytes rather than padding and converting to a string.
> 
> ```
> from outlines import models, generate
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
>  
> llm = AutoModelForCausalLM.from_pretrained("THUDM/glm-4-9b-chat",trust_remote_code=True, device_map="auto")
> tokenizer = AutoTokenizer.from_pretrained("THUDM/glm-4-9b-chat", trust_remote_code=True)
>  
> model = models.Transformers(llm,tokenizer)
> 
> generator = generate.choice(model, ['和长', '本代模'])
> input = '我们在一些经典任务上对 GLM-4-9B-Chat 模型进行了评测,并得到了如下的结果'
> 
> print(generator(input))
> # '和长'
> ```
> 
> Could you please help me test [this PR](https://github.com/dottxt-ai/outlines/pull/1153) and ensure it resolves the issues you all have been seeing?
> 
> Preview:
> 
> ```
> pip uninstall -y outlines
> pip install --upgrade git+https://github.com/lapp0/outlines@fix-bpe
> ```

I tried this version of the package. But I met the error that
```
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: libharpcuda.so.0: cannot open shared object file: No such file or directory
```

**Comment by lapp0** [comment]
@sci-m-wang  can you provide the full error? I see a similar error relating to triton in https://github.com/unslothai/unsloth/issues/872

**Comment by Control-derek** [comment]
@sci-m-wang you can disable Dynamo error suppression by
```
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```

**Comment by Control-derek** [comment]
> [@sci-m-wang](https://github.com/sci-m-wang) you can disable Dynamo error suppression by
> 
> ```
> import torch._dynamo
> torch._dynamo.config.suppress_errors = True
> ```
If this doesn't work, try disabling the dynamic graph as well.
```
import torch
torch._dynamo.config.disable = True
```
