### ISSUE TITLE
models.transformers fails when using `device_map="auto"`

### ISSUE THREAD

**Issue by goncalogiga** [outlines-dev/outlines#238]
Hello and thank you for the great work !

I am testing the JSON generation example with a large model which needs to be split between GPUs. I tried using  huggingface's accelerate library by passing the `device_map='auto'` argument to `models.transformers` but it doesn't seem to work:

```python
 class Weapon(str, Enum):
        sword = "sword"
        axe = "axe"
        mace = "mace"
        spear = "spear"
        bow = "bow"
        crossbow = "crossbow"


    class Armor(str, Enum):
        leather = "leather"
        chainmail = "chainmail"
        plate = "plate"


    class Character(BaseModel):
        name: constr(max_length=10)
        age: int
        armor: Armor
        weapon: Weapon
        strength: int


    model = models.transformers("TheBloke/wizardLM-13B-1.0-fp16", device_map="auto")
    sequence = generate.json(model, Character)("Give me a character description")
    print(sequence)
```

```
    Traceback (most recent call last):
  File "/home/testing_outlines/hello_world.py", line 510, in <module>
    model = transformers("TheBloke/wizardLM-13B-1.0-fp16", device_map="auto")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/testing_outlines/hello_world.py", line 481, in transformers
    return TransformersAccelerated(model, tokenizer, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/testing_outlines/hello_world.py", line 470, in __init__
    self.model = model.to(self.device)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/testing_outlines/.venv/lib/python3.11/site-packages/transformers/m
odeling_utils.py", line 1900, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/testing_outlines/.venv/lib/python3.11/site-packages/torch/nn/modul
es/module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/testing_outlines/.venv/lib/python3.11/site-packages/torch/nn/modul
es/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/testing_outlines/.venv/lib/python3.11/site-packages/torch/nn/modul
es/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/testing_outlines/.venv/lib/python3.11/site-packages/torch/nn/modul
es/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/testing_outlines/.venv/lib/python3.11/site-packages/torch/nn/modul
es/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/testing_outlines/.venv/lib/python3.11/site-packages/torch/nn/modul
es/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_
blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^
NotImplementedError: Cannot copy out of meta tensor; no data!
```

The exception is raised by `model.to(self.device)` as it attempts to load the model to CPU (since no device parameter was passed to `transformers`) which will not work when the model is being handled by accelerate. Passing `device="cuda"` does not work either since it throws a `torch.cuda.OutOfMemoryError` exception that should have been prevented by accelerate.

**Comment by BramVanroy** [comment]
I have a similar issue when using a `transformers` model. From my testing it does not seem possible to readily use techniques like `load_in_4bit` or `device_map="auto"` for improved inference speed. the `.to` call is the blocker here because it will trigger an error like this:

> ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
