### ISSUE TITLE
Logit and mask size mismatch

### ISSUE THREAD

**Issue by abhigya-sodani** [outlines-dev/outlines#249]
The following code:
```
import outlines.models as models 
import outlines.text.generate as generate

model = models.transformers("facebook/opt-350m")

prompt = "Is 1+1 = 2"
guided = generate.regex(model,r"\s*([Yy]es|[Nn]o|[Nn]ever|[Aa]lways)",max_tokens=30)(prompt)
print(guided)
```
Gives the following error
```
Traceback (most recent call last):
  File "C:\Users\Abhigya Sodani\LLM-VM\src\llm_vm\completion\regex_test.py", line 9, in <module>
    guided = generate.regex(model,r"\s*([Yy]es|[Nn]o|[Nn]ever|[Aa]lways)",max_tokens=30)(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\site-packages\outlines\text\generate\sequence.py", line 224, in __call__
    updated_token_ids, _ = self.step(
                           ^^^^^^^^^^
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\site-packages\outlines\text\generate\sequence.py", line 82, in step
    probs = self.create_proposal(token_ids[:, num_prompt_tokens:], probs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abhigya Sodani\AppData\Local\Programs\Python\Python311\Lib\site-packages\outlines\text\generate\regex.py", line 147, in create_proposal
    return logits + mask
           ~~~~~~~^~~~~~
RuntimeError: The size of tensor a (50272) must match the size of tensor b (50265) at non-singleton dimension 1
```
Am I doing something wrong?

**Comment by rlouf** [comment]
Possible duplicate with #213
