### ISSUE TITLE
Tensor size error in example trying to do prompting primitives alongside JSON generation

### ISSUE THREAD

**Issue by veezbo** [outlines-dev/outlines#286]
This is the traceback of the runtime error I receive:

```
Traceback (most recent call last):
  File "/home/ubuntu/outlines/examples/dating_profile.py", line 74, in <module>
    profile = text.generate.json(model, DatingProfile)(prompt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/outlines/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/outlines/venv/lib/python3.11/site-packages/outlines/text/generate/sequence.py", line 224, in __call__
    updated_token_ids, _ = self.step(
                           ^^^^^^^^^^
  File "/home/ubuntu/outlines/venv/lib/python3.11/site-packages/outlines/text/generate/sequence.py", line 82, in step
    probs = self.create_proposal(token_ids[:, num_prompt_tokens:], probs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/outlines/venv/lib/python3.11/site-packages/outlines/text/generate/regex.py", line 147, in create_proposal
    return logits + mask
           ~~~~~~~^~~~~~
RuntimeError: The size of tensor a (50272) must match the size of tensor b (50265) at non-singleton dimension 1
```

And this is the code I attempt to run, which includes both prompting primitives and JSON generation. Note that I tried a variety of models available in transformers, including `facebook/opt-1.3b` as well as `microsoft/phi-1_5` which gave me a similar tensor size runtime error.

```
from dataclasses import dataclass
from enum import Enum
from pydantic import BaseModel, conlist

import outlines.models as models
import outlines.text as text


class QuestionChoice(str, Enum):
    A = "The key to my heart is",
    B = "The first item on my bucket list is",
    C = "Perks of dating me",
    D = "Message me if you also love",
    E = "My ideal first date is",


class DatingProfile(BaseModel):
    bio: str
    job: str
    interests: conlist(str, min_length=1, max_length=5)
    question: QuestionChoice
    answer: str


@dataclass
class Example:
    description: str
    profile: DatingProfile


samples: list[Example] = [
    Example(
        description="I'm an author and former professional soccer player living in Seattle who publishes popular fiction books. A typical day for me starts by hanging out with my cat, drinking a coffee, and reading as much as I can in a few hours. Then, I'll prepare a quick smoothie before starting to write for a few hours, take a break with soccer or running a few miles, and finally meet friends for dinner at a new, hip restaurant in the evening. Sometimes we go axe-throwing afterwards, or play poker, or watch a comedy show, or visit a dive bar. On my vacations, I travel extensively to countries South America, Europe, and Asia, with the goal of visiting them all!",
        profile=DatingProfile(
            bio="Adventurer, dreamer, author, and soccer enthusiast living in Seattle. Life’s too short to waste time so I make the most of each day by exploring new places and playing with my friends on the pitch. What’s your favorite way to get out and have fun?",
            interests=["Soccer", "Travel", "Friends", "Books", "Fluffy Animals"],
            job="Famous Soccer Player -> Famous Author",
            question=QuestionChoice.B,
            answer="swim in all seven oceans!",
        )
    )
]


@text.prompt
def dating_profile_prompt(description: str, examples: list[Example]):
    """
    You are a world-renowned matchmaker who understands the modern dating market. You are tasked with generating a dating app profile for a client based on a self-written description that shows off their strengths and maximizes their likelihood of finding a match on a dating app.
    {% for example in examples %}
    Description: {{ example.description }}
    Profile: {{ example.profile }}
    {% endfor %}
    Description: {{ description }}
    Profile: """


new_description = "I'm a laid-back lawyer proficient who spends a lot of his free-time gaming. I work in a corporate office, but ended up here after the start-up I cofounded got acquired, so still play ping pong with my cool coworkers every day. I have a bar at home where I make cocktails, which is great for entertaining friends. I secretly like to wear suits and get a new one tailored every few months. I also like weddings because I get to wear those suits, and it's a good excuse for a date. I watch the latest series because I'm paying, with my hard-earned money, for every streaming service."

model = models.transformers('facebook/opt-1.3b', device="cuda")
prompt = dating_profile_prompt(description=new_description, examples=samples)
profile = text.generate.json(model, DatingProfile)(prompt)
print(profile)

parsed_profile = DatingProfile.model_validate_json(profile)
print(parsed_profile)

```

**Comment by brandonwillard** [comment]
Which version are you running?  We added a fix for this issue in https://github.com/outlines-dev/outlines/pull/236 but haven't created a new release just yet.

**Comment by veezbo** [comment]
Oh thanks! I was running this with the latest available `outlines` on pip.

What's the best way to build it locally so I can test with that fix?

**Comment by brandonwillard** [comment]
`pip install git+https://github.com/outlines-dev/outlines` should install the current `main` branch.

**Comment by veezbo** [comment]
Thanks for helping resolve this! I was able to confirm that my code runs as expected with the latest `outlines` code (i.e. with a local installation)
