### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by tom-doerr** [outlines-dev/outlines#425]
### Describe the issue as clearly as possible:

I wanted to run one of the examples.

### Steps/code to reproduce the bug:

```python
from enum import Enum
from pydantic import BaseModel, constr

import outlines
import torch


class Weapon(str, Enum):
    sword = "sword"
    axe = "axe"
    mace = "mace"
    spear = "spear"
    bow = "bow"
    crossbow = "crossbow"


class Armor(str, Enum):
    leather = "leather"
    chainmail = "chainmail"
    plate = "plate"


class Character(BaseModel):
    name: constr(max_length=10)
    age: int
    armor: Armor
    weapon: Weapon
    strength: int


model = outlines.models.transformers("gpt2", device="cuda")

# Construct guided sequence generator
generator = outlines.generate.json(model, Character, max_tokens=100)

# Draw a sample
rng = torch.Generator(device="cuda")
rng.manual_seed(789001)

sequence = generator("Give me a character description", rng=rng)
print(sequence)
# {
#   "name": "clerame",
#   "age": 7,
#   "armor": "plate",
#   "weapon": "mace",
#   "strength": 4171
# }

sequence = generator("Give me an interesting character description", rng=rng)
print(sequence)
# {
#   "name": "piggyback",
#   "age": 23,
#   "armor": "chainmail",
#   "weapon": "sword",
#   "strength": 0
# }

parsed = Character.model_validate_json(sequence)
print(parsed)
# name='piggyback' age=23 armor=<Armor.chainmail: 'chainmail'> weapon=<Weapon.sword: 'sword'> strength=0
```

### Expected result:

```shell
Just the parsed info.
```

### Error message:

```shell
name='El Jinnin' age=12 armor=<Armor.plate: 'plate'> weapon=<Weapon.sword: 'sword'> strength=14
name='Throne of ' age=2013 armor=<Armor.leather: 'leather'> weapon=<Weapon.mace: 'mace'> strength=1024004800000000019100111

Traceback (most recent call last):
  File "/home/conic/llm_experimentation/./outlines_test.py", line 64, in <module>
    parsed = Character.model_validate_json(sequence)
  File "/home/conic/.local/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Character
  JSON input should be string, bytes or bytearray [type=json_type, input_value=Character(name='Throne of...24004800000000019100111), input_type=Character]
    For further information visit https://errors.pydantic.dev/2.5/v/json_type
```

### Outlines/Python version information:

```python
File "/home/conic/llm_experimentation/./version_info.py", line 3, in <module>
    import outlines; print("Outlines", outlines.__version__)AttributeError: module 'outlines' has no attribute '__version__'
```

**Comment by tom-doerr** [comment]
Parsing seems unnecessary, sequence is already of type Character

**Comment by rlouf** [comment]
This is indeed an error in the README, I apologise. We recently made the code output `BaseModel` instances instead of dictionaries and forgot to reflect this change in the README. Thank you!

**Comment by rlouf** [comment]
Just fixed the example, closing.
