### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonschema.protocols'

### ISSUE THREAD

**Issue by libinpg** [outlines-dev/outlines#538]
### Describe the issue as clearly as possible:

![screenshot20240115](https://github.com/outlines-dev/outlines/assets/101452633/ce20b1c7-761b-4b4d-b012-b6221521ed13)

### Steps/code to reproduce the bug:

```python
import outlines
```

### Expected result:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/outlines/__init__.py", line 2, in <module>
    import outlines.generate
  File "/usr/local/lib/python3.8/dist-packages/outlines/generate/__init__.py", line 1, in <module>
    from .api import cfg, choice, format, json, regex, text
  File "/usr/local/lib/python3.8/dist-packages/outlines/generate/api.py", line 9, in <module>
    from outlines.fsm.json_schema import build_regex_from_object, get_schema_from_signature
  File "/usr/local/lib/python3.8/dist-packages/outlines/fsm/json_schema.py", line 7, in <module>
    from jsonschema.protocols import Validator
ModuleNotFoundError: No module named 'jsonschema.protocols'
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/outlines/__init__.py", line 2, in <module>
    import outlines.generate
  File "/usr/local/lib/python3.8/dist-packages/outlines/generate/__init__.py", line 1, in <module>
    from .api import cfg, choice, format, json, regex, text
  File "/usr/local/lib/python3.8/dist-packages/outlines/generate/api.py", line 9, in <module>
    from outlines.fsm.json_schema import build_regex_from_object, get_schema_from_signature
  File "/usr/local/lib/python3.8/dist-packages/outlines/fsm/json_schema.py", line 7, in <module>
    from jsonschema.protocols import Validator
ModuleNotFoundError: No module named 'jsonschema.protocols'
```

### Outlines/Python version information:

```python
python 3.8
```

### Context for the issue:

Linux version 5.4.0-156-generic (buildd@lcy02-amd64-078) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023

**Comment by rlouf** [comment]
What is the version of `jsonschema`?

**Comment by Theodotus1243** [comment]
For me update to `jsonschema-4.21.1` helped
