### ISSUE TITLE
Error when FSM receives final state as input

### ISSUE THREAD

**Issue by saattrupdan** [outlines-dev/outlines#716]
### Describe the issue as clearly as possible:

I've encountered an error during the use of `outlines` with JSON generation. See the full traceback below.

It seems as though the [`FSM.next_state`](https://github.com/outlines-dev/outlines/blob/d938678d6e6cb5ddd7b87e92d4badb14e9e56ae8/outlines/fsm/fsm.py#L62-L84) needs to deal with the case that `state == -1`, i.e., that for some reason the final state is inserted into `next_state`.

Could this be fixed if we simply return `self.final_state` if `state == self.final_state`?

### Steps/code to reproduce the bug:

Hard to reproduce, because it seems to not always happen. It happens during the vLLM integration with `JSONLogitsProcessor`. It might be due to a race condition happening, that we reach the final state in another thread.

### Expected result:

Not an error.

### Error message:

```shell
Traceback (most recent call last):
  File "/home/ubuntu/.venv/bin/scandeval", line 8, in <module>
    sys.exit(benchmark())
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/cli.py", line 282, in benchmark
    benchmarker(model=models)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 689, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 536, in benchmark
    record = self._benchmark_single(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmarker.py", line 641, in _benchmark_single
    results, metadata_dict = dataset(model_id)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 566, in __call__
    return self.benchmark(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/benchmark_dataset.py", line 188, in benchmark
    scores = generate(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/generation.py", line 155, in generate
    scores = update_scores(scores=scores, benchmark_config=benchmark_config)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/generation.py", line 134, in update_scores
    test_scores = generate_single_iteration(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/generation.py", line 300, in generate_single_iteration
    model_output, extracted_labels = generate_batch(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/generation.py", line 471, in generate_batch
    model_output = model.generate(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 198, in generate
    raw_outputs = self._model.generate(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 182, in generate
    return self._run_engine(use_tqdm)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/scandeval/vllm_models.py", line 327, in _run_engine_with_fixed_progress_bars                                                                                                                     step_outputs = self.llm_engine.step()
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 812, in step
    all_outputs = self._run_workers(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1006, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 225, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 572, in execute_model
    output = self.model.sample(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 296, in sample
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 74, in forward                                                                                                                                      logits = _apply_logits_processors(logits, sampling_metadata)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 156, in _apply_logits_processors
    logits_row = logits_processor(token_ids, logits_row)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/outlines/serve/vllm.py", line 77, in __call__
    self.fsm_state[seq_id] = self.fsm.next_state(
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 178, in next_state
    last_token_to_end_state = self.states_to_token_maps[state]
KeyError: -1
```

### Outlines/Python version information:

Version information
<details>

Outlines version:

```
0.0.34
```

Python version:

```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```

Pip freeze:

```
absl-py==2.1.0
accelerate==0.26.1
ai2-olmo==0.2.4
aiohttp==3.9.1
aioprometheus==23.12.0
aiosignal==1.3.1
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
anyio==4.2.0
async-timeout==4.0.3
attrs==23.2.0
bert-score==0.3.13
bitsandbytes==0.42.0
boto3==1.34.41
botocore==1.34.41
cached-path==1.5.1
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
chex==0.1.85
click==8.1.7
cloudpickle==3.0.0
contourpy==1.2.0
cupy-cuda12x==12.1.0
cycler==0.12.1
datasets==2.16.1
demjson3==3.0.6
dill==0.3.7
diskcache==5.6.3
distro==1.9.0
einops==0.7.0
etils==1.6.0
evaluate==0.4.1
exceptiongroup==1.2.0
fastapi==0.109.0
fastrlock==0.8.2
filelock==3.12.4
flash-attn==2.5.5
flax==0.8.1
fonttools==4.47.2
frozenlist==1.4.1
fsspec==2023.10.0
google-api-core==2.17.0
google-auth==2.27.0
google-cloud-core==2.4.1
google-cloud-storage==2.14.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.62.0
h11==0.14.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.26.0
huggingface-hub==0.19.4
idna==3.6
importlib-resources==6.1.1
interegular==0.3.3
jax==0.4.24
jaxlib==0.4.24
Jinja2==3.1.3
jmespath==1.0.1
joblib==1.3.2
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
lark==1.1.9
Levenshtein==0.24.0
llvmlite==0.42.0
lm-format-enforcer==0.8.3
markdown-it-py==3.0.0
MarkupSafe==2.1.4
matplotlib==3.8.2
mdurl==0.1.2
ml-dtypes==0.3.2
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.4
multiprocess==0.70.15
nest-asyncio==1.6.0
networkx==3.2.1
ninja==1.11.1.1
nltk==3.8.1
numba==0.59.0
numpy==1.26.3
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
omegaconf==2.3.0
openai==1.12.0
opt-einsum==3.3.0
optax==0.1.8
orbax-checkpoint==0.5.1
orjson==3.9.12
outlines==0.0.34
packaging==23.2
pandas==2.2.1
pillow==10.2.0
protobuf==3.20.3
psutil==5.9.8
pyarrow==15.0.0
pyarrow-hotfix==0.6
pyasn1==0.5.1
pyasn1-modules==0.3.0
pydantic==2.6.0
pydantic_core==2.16.1
Pygments==2.17.2
pyinfer==0.0.3
pynvml==11.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
python-dotenv==1.0.1
pytz==2023.3.post1
PyYAML==6.0.1
quantile-python==1.1
rapidfuzz==3.6.1
ray==2.9.1
referencing==0.32.1
regex==2023.12.25
requests==2.31.0
responses==0.18.0
rich==13.7.0
rouge_score==0.1.2
rpds-py==0.17.1
rsa==4.9
s3transfer==0.10.0
sacremoses==0.1.1
safetensors==0.4.2
ScandEval==12.1.0
scikit-learn==1.4.0
scipy==1.12.0
sentencepiece==0.1.99
seqeval==1.2.2
six==1.16.0
sniffio==1.3.0
starlette==0.35.1
sympy==1.12
tabulate==0.9.0
tensorstore==0.1.52
termcolor==2.4.0
threadpoolctl==3.2.0
tiktoken==0.5.2
tokenizers==0.15.1
toolz==0.12.1
torch==2.1.2
tqdm==4.66.1
transformers==4.38.1
triton==2.1.0
typing_extensions==4.9.0
tzdata==2023.4
urllib3==2.0.7
uvicorn==0.27.0
uvloop==0.19.0
vllm==0.3.1
watchfiles==0.21.0
websockets==12.0
xformers==0.0.23.post1
xxhash==3.4.1
yarl==1.9.4
zipp==3.17.0
```
</details>

### Context for the issue:

Hinders running our evaluation framework on the new Qwen models, and thus inclusion of these on [the official leaderboards](https://scandeval.com/).

**Comment by saattrupdan** [comment]
@rlouf I can create a PR that simply returns the final state if the final state is supplied as input, if needed?

**Comment by rlouf** [comment]
Yes please!
