### ISSUE TITLE
Could not translate the instance {} to a regular expression

### ISSUE THREAD

**Issue by blueridanus** [outlines-dev/outlines#749]
### Describe the issue as clearly as possible:

`outlines` errors out trying to parse the JSON schema for Vega-Lite.

### Steps/code to reproduce the bug:

```python
import requests
import json
from outlines.fsm.json_schema import build_regex_from_schema

vega_schema = requests.get("https://vega.github.io/schema/vega-lite/v5.json").json()

# patching up the document since outlines doesn't support "format": "..." (color-hex, uri, uri-reference used in schema)
def patch_schema(schema):
    try:
        if isinstance(schema["format"], str):
            del schema["format"]
    except KeyError:
        pass
    for v in schema.values():
        if isinstance(v, dict):
            patch_schema(v)

    return schema

vega_schema = patch_schema(vega_schema)

build_regex_from_schema(json.dumps(vega_schema))
```

### Expected result:

```shell
Schema gets happily built. :)
```

### Error message:

```shell
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    build_regex_from_schema(json.dumps(vega_schema))
  File "../outlines/fsm/json_schema.py", line 83, in build_regex_from_schema
    return to_regex(resolver, content, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 230, in to_regex
    return to_regex(resolver, instance, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 185, in to_regex
    subregexes = [
                 ^
  File "../outlines/fsm/json_schema.py", line 186, in <listcomp>
    to_regex(resolver, t, whitespace_pattern) for t in instance["anyOf"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 230, in to_regex
    return to_regex(resolver, instance, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 142, in to_regex
    subregex += to_regex(resolver, value, whitespace_pattern)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 230, in to_regex
    return to_regex(resolver, instance, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 156, in to_regex
    subregex += to_regex(resolver, value, whitespace_pattern)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 230, in to_regex
    return to_regex(resolver, instance, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 156, in to_regex
    subregex += to_regex(resolver, value, whitespace_pattern)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 185, in to_regex
    subregexes = [
                 ^
  File "../outlines/fsm/json_schema.py", line 186, in <listcomp>
    to_regex(resolver, t, whitespace_pattern) for t in instance["anyOf"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 230, in to_regex
    return to_regex(resolver, instance, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 320, in to_regex
    value_pattern = to_regex(
                    ^^^^^^^^^
  File "../outlines/fsm/json_schema.py", line 356, in to_regex
    raise NotImplementedError(
NotImplementedError: Could not translate the instance {} to a
    regular expression. Make sure it is valid to the JSON Schema specification. If
    it is, please open an issue on the Outlines repository
```

### Outlines/Python version information:

Version information
<details>
0.0.36
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
</details>

**Comment by rlouf** [comment]
Thank you for opening an issue! Why do you need to remove the `format` property?

**Comment by blueridanus** [comment]
Ah, I did that as a workaround. From the comment on the sample:
```python
# patching up the document since outlines doesn't support "format": "..." (color-hex, uri, uri-reference are used in schema)
```
Here's the error if I don't patch the schema to remove `format`:
```
Traceback (most recent call last):
  File "test.py", line 51, in <module>
    build_regex_from_schema(json.dumps(vega_schema))
  File "outlines/fsm/json_schema.py", line 83, in build_regex_from_schema
    return to_regex(resolver, content, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "outlines/fsm/json_schema.py", line 230, in to_regex
    return to_regex(resolver, instance, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "outlines/fsm/json_schema.py", line 185, in to_regex
    subregexes = [
                 ^
  File "outlines/fsm/json_schema.py", line 186, in <listcomp>
    to_regex(resolver, t, whitespace_pattern) for t in instance["anyOf"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "outlines/fsm/json_schema.py", line 230, in to_regex
    return to_regex(resolver, instance, whitespace_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "outlines/fsm/json_schema.py", line 142, in to_regex
    subregex += to_regex(resolver, value, whitespace_pattern)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "outlines/fsm/json_schema.py", line 268, in to_regex
    raise NotImplementedError(
NotImplementedError: Format uri is not supported by Outlines
```

**Comment by RobinPicard** [comment]
It seems to be because your json schema contains:
```
"type": "array",
"items": {}
```
somewhere in it. 

An easy fix could to be to turn `if "items" in instance:` into `if instance.get("items"):` in the `json_schema.py` file to ignore empty "items" objects
