### ISSUE TITLE
outlines with llamacpp has KeyError over 'n_gpu_layers'

### ISSUE THREAD

**Issue by AndreaRiboni** [outlines-dev/outlines#761]
### Describe the issue as clearly as possible:

i have used llamacpp on itself or via langchain with no problems. When loading the same gguf model using outlines' llamacpp wrapper, i get a keyerror

### Steps/code to reproduce the bug:

```python
install llamacpp:

`MAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python==0.2.43 --no-cache-dir`

install outlines:
`pip install outlines`

load the model:

import outlines
llm = outlines.models.llamacpp(
       model_path,
       device="cuda", 
       model_kwargs={
          'n_ctx': context_size,
          'n_gpu_layers': -1
       }
)
```

### Expected result:

```shell
the model should be loaded correctly
```

### Error message:

```shell
Traceback (most recent call last):
  File "/usr/src/app/llm-exposer.py", line 56, in <module>
    llm_wrapper = LLMModel(default_model)
  File "/usr/src/app/model.py", line 29, in __init__
    self.load_model()
  File "/usr/src/app/model.py", line 32, in load_model
    self.llm = outlines.models.llamacpp(
  File "/usr/local/lib/python3.10/dist-packages/outlines/models/llamacpp.py", line 29, in llamacpp
    model_kwargs["n_gpu_layers"].setdefault(-1)
KeyError: 'n_gpu_layers'
```

### Outlines/Python version information:

Version information
<details>
```
(command output here)
```
</details>

**Comment by isamu-isozaki** [comment]
I think this is fixed in [here](https://github.com/outlines-dev/outlines/issues/743). Not sure if the latest version includes it though

**Comment by rlouf** [comment]
I completely overhauled the llama.cpp integration in #779 and this shouldn't be an issue anymore!
